// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: pkg/api/stock_price.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Stock symbol (e.g., "AAPL" for Apple)
}

func (x *StockPriceRequest) Reset() {
	*x = StockPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_stock_price_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceRequest) ProtoMessage() {}

func (x *StockPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_stock_price_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceRequest.ProtoReflect.Descriptor instead.
func (*StockPriceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_stock_price_proto_rawDescGZIP(), []int{0}
}

func (x *StockPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type StockPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price     float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp string  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *StockPriceResponse) Reset() {
	*x = StockPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_stock_price_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPriceResponse) ProtoMessage() {}

func (x *StockPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_stock_price_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPriceResponse.ProtoReflect.Descriptor instead.
func (*StockPriceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_stock_price_proto_rawDescGZIP(), []int{1}
}

func (x *StockPriceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockPriceResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_pkg_api_stock_price_proto protoreflect.FileDescriptor

var file_pkg_api_stock_price_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x60, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0xbf, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x58, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_stock_price_proto_rawDescOnce sync.Once
	file_pkg_api_stock_price_proto_rawDescData = file_pkg_api_stock_price_proto_rawDesc
)

func file_pkg_api_stock_price_proto_rawDescGZIP() []byte {
	file_pkg_api_stock_price_proto_rawDescOnce.Do(func() {
		file_pkg_api_stock_price_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_stock_price_proto_rawDescData)
	})
	return file_pkg_api_stock_price_proto_rawDescData
}

var file_pkg_api_stock_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_stock_price_proto_goTypes = []interface{}{
	(*StockPriceRequest)(nil),  // 0: stock_price.StockPriceRequest
	(*StockPriceResponse)(nil), // 1: stock_price.StockPriceResponse
}
var file_pkg_api_stock_price_proto_depIdxs = []int32{
	0, // 0: stock_price.StockPriceService.GetStockPrice:input_type -> stock_price.StockPriceRequest
	0, // 1: stock_price.StockPriceService.GetStockPriceStream:input_type -> stock_price.StockPriceRequest
	1, // 2: stock_price.StockPriceService.GetStockPrice:output_type -> stock_price.StockPriceResponse
	1, // 3: stock_price.StockPriceService.GetStockPriceStream:output_type -> stock_price.StockPriceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_stock_price_proto_init() }
func file_pkg_api_stock_price_proto_init() {
	if File_pkg_api_stock_price_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_stock_price_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_stock_price_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_stock_price_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_stock_price_proto_goTypes,
		DependencyIndexes: file_pkg_api_stock_price_proto_depIdxs,
		MessageInfos:      file_pkg_api_stock_price_proto_msgTypes,
	}.Build()
	File_pkg_api_stock_price_proto = out.File
	file_pkg_api_stock_price_proto_rawDesc = nil
	file_pkg_api_stock_price_proto_goTypes = nil
	file_pkg_api_stock_price_proto_depIdxs = nil
}
